#!/usr/bin/env bash

## Check if CIDR block is provided as an argument: EXAMPLE: 172.31.0.0/16
if [ -z "$1" ]; then
  echo "Usage: $0 <CIDR_BLOCK>"
  exit 1
fi
CIDR_BLOCK=$1   

## Create our VPC
VPC_ID=$(aws ec2 create-vpc \
--cidr-block "$CIDR_BLOCK" \
--region eu-west-1 \
--tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=
MyVPC}]' \
--query 'Vpc.VpcId' \
--output text)

echo "Created VPC with ID: $VPC_ID"

## Enable DNS Hostnames for the VPC
aws ec2 modify-vpc-attribute \
  --vpc-id $VPC_ID \
  --enable-dns-hostnames



## Create an IGW
IGW_ID=$(aws ec2 create-internet-gateway \
--tag-specifications 'ResourceType=internet-gateway,Tags=[{Key=Name,Value=MyIGW}]' \
--query 'InternetGateway.InternetGatewayId' \
--output text)
echo "Created Internet Gateway with ID: $IGW_ID"

## Attach the IGW to our VPC
aws ec2 attach-internet-gateway \
--internet-gateway-id $IGW_ID \
--vpc-id $VPC_ID

## Create a Public Subnet
SUBNET_ID=$(aws ec2 create-subnet \
--vpc-id $VPC_ID \
--cidr-block $CIDR_BLOCK \
--tag-specifications 'ResourceType=subnet,Tags=[{Key=Name,Value=MyPublicSubnet}]' \
--query 'Subnet.SubnetId' \
--output text) 
echo "Created Subnet with ID: $SUBNET_ID"
 
## Enable Auto-assign Public IP on the Subnet
aws ec2 modify-subnet-attribute \
  --subnet-id $SUBNET_ID \
  --map-public-ip-on-launch


 ## Add Route Table
 ROUTE_TABLE_ID=$(aws ec2 describe-route-tables \
    --filters "Name=vpc-id,Values=$VPC_ID" \
    --query "RouteTables[0].RouteTableId" \
    --output text)
echo "Using Route Table with ID: $ROUTE_TABLE_ID"

## Associate a route to the IGW
ASSOCIATION_ID=$(aws ec2 associate-route-table --route-table-id $ROUTE_TABLE_ID --subnet-id $SUBNET_ID --query 'AssociationId' --output text)
echo "Associated Route Table with ID: $ASSOCIATION_ID"

## Create a route to the IGW
aws ec2 create-route \
  --route-table-id $ROUTE_TABLE_ID \
  --destination-cidr-block 0.0.0.0/0 \
  --gateway-id $IGW_ID

