#!/bin/bash

if [ -z "$1" ]; then
  echo "Usage: delete_vpc <VPC_ID> <IGW_ID> <SUBNET_ID> <ROUTE_TABLE_ID> <ASSOCIATION_ID>"
  exit 1
fi

VPC_ID=$1
IGW_ID=$2
SUBNET_ID=$3
ROUTE_TABLE_ID=$4
ASSOCIATION_ID=$5

echo "Detaching Internet Gateway"
aws ec2 detach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID

echo "Deleting Internet Gateway"
aws ec2 delete-internet-gateway --internet-gateway-id $IGW_ID

echo "Disassociating Route Table"
aws ec2 disassociate-route-table --association-id $ASSOCIATION_ID

echo "Deleting Subnet"
aws ec2 delete-subnet --subnet-id $SUBNET_ID

echo "Deleting Route Table"
aws ec2 delete-route-table --route-table-id $ROUTE_TABLE_ID

echo "Deleting VPC"
aws ec2 delete-vpc --vpc-id $VPC_ID

echo "VPC Deletion Completed"

##Verification
#aws ec2 describe-vpcs --vpc-ids $VPC_ID
#aws ec2 describe-subnets --subnet-ids $SUBNET_ID
#aws ec2 describe-route-tables --route-table-ids $ROUTE_TABLE_ID
#aws ec2 describe-internet-gateways --internet-gateway-ids $IGW_ID
#./delete_vpc.sh $VPC_ID $IGW_ID $SUBNET_ID $ROUTE_TABLE_ID $ASSOCIATION_ID