#!/usr/bin/env bash

# when to sync objects
echo "== delete objects"

# Exit immediately if a command exits with a non-zero status
set -e  

#Check for bucket name 
if [ -z "$1" ]; then
  echo "There needs to be a bucket name eg.  ./bucket djibril-bucket-example"
  exit 1
fi

BUCKET_NAME=$1

DELETE_JSON=$(aws s3api list-objects-v2 \
  --bucket $BUCKET_NAME \
  --query 'Contents[].Key' \
  | jq -n '{Objects: [inputs | .[] | {Key: .}]}')

aws s3api delete-objects --bucket $BUCKET_NAME --delete "$DELETE_JSON"

  