#!/usr/bin/env bash

# wher to put one the object
echo "== put object"

#Check for bucket name 
if [ -z "$1" ]; then
  echo "There needs to be a bucket filename eg.  ./bucket djibril-bucket-example"
  exit 1
fi

#Check for filename 
if [ -z "$2" ]; then
  echo "There needs to be a bucket filename eg.  ./bucket djibril-bucket-example"
  exit 1
fi

BUCKET_NAME=$1
FILE_NAME=$2

OBJECT_KEY=$(basename "$FILE_NAME")

aws s3api put-object \
  --bucket "$BUCKET_NAME" \
  --body "$FILE_NAME" \
  --key "$OBJECT_KEY"