#!/bin/bash

# Force LocalStack
export AWS_ACCESS_KEY_ID=test
export AWS_SECRET_ACCESS_KEY=test
export AWS_DEFAULT_REGION=us-east-1
export AWS_ENDPOINT_URL=http://localhost:4566

echo "== deploying sns basic =="

STACK_NAME="sns-basic"
TEMPLATE_FILE="template.yml"
aws cloudformation deploy \
  --stack-name $STACK_NAME \
  --template-file $TEMPLATE_FILE \
  --region us-east-1 \
  --no-fail-on-empty-changeset
