AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Python for LocalStack

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

  MyPythonLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: my-python-lambda
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 10
      MemorySize: 128
      Code:
        S3Bucket: my-lambda-artifacts-bucket
        S3Key: function.zip
