#!/usr/bin/env bash

echo "== deploy s3 bucket via CFN =="

STACK_NAME="s3-bucket-stack"
aws cloudformation deploy \
    --template-file template.yaml \
    --no-execute-changeset \
    --region us-east-1 \
    --stack-name $STACK_NAME
    